export const LOAD_MOVIES_REQUEST = 'LOAD_MOVIES_REQUEST';
export const LOAD_MOVIES_SUCCEEDED = 'LOAD_MOVIES_SUCCEEDED';
export const LOAD_MOVIES_FAILED = 'LOAD_MOVIES_FAILED';

export const LOAD_IMDBINFO_REQUEST = 'LOAD_IMDBINFO_REQUEST';
export const LOAD_IMDBINFO_SUCCEEDED = 'LOAD_IMDBINFO_SUCCEEDED';
export const LOAD_IMDBINFO_FAILED = 'LOAD_IMDBINFO_FAILED';

export const CLOSE_INFO_MODAL = 'CLOSE_INFO_MODAL';
